Project Name : shalomproject
Modules:
    marketModule:
        formComponent(name=["enquiries"],params=["enquiriesModel"])
        formComponent(name=["bookings"],params=["bookingsModel"])
        
Models:
    enquiriesModel:StandardModel
    bookingsModel:StandardModel
